/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DlcxGqzcgK5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function DisplayMason() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="flex justify-between items-center px-6 py-4">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <img src="/1024-mac.png" className="w-8 h-8" />
          <span className="font-bold text-xl lg:text-2xl">DisplayMason</span>
        </Link>
        <nav className="md:flex items-center gap-6 hidden">
          <Link href="#features" className="font-medium text-sm hover:underline" prefetch={false}>
            Features
          </Link>
          <Link href="#testimonials" className="font-medium text-sm hover:underline" prefetch={false}>
            Testimonials
          </Link>
        </nav>
        <Link
          href="https://apps.apple.com/app/displaymason/id123456789"
          target="_blank"
          className="md:inline-flex hidden"
        >
          <Button variant="secondary">Get DisplayMason Now!</Button>
        </Link>
      </header>
      <main className="flex-1">
        <section className="flex flex-col items-center gap-4 mx-auto px-6 py-24 p-4 max-w-5xl text-center container">
          <img src="/1024-mac.png" alt="DisplayMason Logo" className="items-center w-32 h-32" />
          <h1 className="font-bold text-xl md:text-4xl">
            Intuitive Display Alignment for Your Mac
          </h1>
          <p className="mt-4 text-muted-foreground">
            DisplayMason brings intuitive display alignment to macOS.
            Press {' '}
            <kbd className="bg-secondary/20 shadow-inner px-2 py-1 rounded text-md">⌘ + R</kbd>
            {' '} and move your mouse to the edge of the screen where you want to snap your other display.
          </p>
          <div className="flex gap-4 mt-6">
            <Button variant="default">Try for Free</Button>
            <Button variant="secondary">Buy for $15</Button>
          </div>
          <p className="mt-2 text-muted-foreground text-sm">Requires macOS Monterey (12.0) or newer.</p>
          <img src="/header-image.png" alt="App screenshot" className="shadow-inner mt-12 rounded w-full" />
        </section>
        <section id="features" className="bg-gradient-to-b from-secondary/10 to-secondary/20 shadow-inner px-6 py-20">
          <div className="gap-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 mx-auto max-w-5xl container">
            <div className="flex flex-col items-center gap-4">
              <DiscIcon className="w-12 h-12 text-secondary" />
              <h3 className="font-bold text-xl">Display Management</h3>
              <p className="text-center text-muted-foreground">
                Easily configure and control multiple displays with a user-friendly interface.
              </p>
            </div>
            <div className="flex flex-col items-center gap-4">
              <ScalingIcon className="w-12 h-12 text-secondary" />
              <h3 className="font-bold text-xl">Precise Resizing</h3>
              <p className="text-center text-muted-foreground">
                Resize and position your displays with pixel-perfect accuracy.
              </p>
            </div>
            <div className="flex flex-col items-center gap-4">
              <BotIcon className="w-12 h-12 text-secondary" />
              <h3 className="font-bold text-xl">Automation</h3>
              <p className="text-center text-muted-foreground">
                Create custom display profiles and automate your workflow.
              </p>
            </div>
            <div className="flex flex-col items-center gap-4">
              <KeyboardIcon className="w-12 h-12 text-secondary" />
              <h3 className="font-bold text-xl">Hotkey Support</h3>
              <p className="text-center text-muted-foreground">
                Quickly access your most-used display settings with customizable hotkeys.
              </p>
            </div>
            <div className="flex flex-col items-center gap-4">
              <AppleIcon className="w-12 h-12 text-secondary" />
              <h3 className="font-bold text-xl">Retina Support</h3>
              <p className="text-center text-muted-foreground">
                Enjoy crisp, high-resolution display settings for your Retina-enabled devices.
              </p>
            </div>
            <div className="flex flex-col items-center gap-4">
              <SettingsIcon className="w-12 h-12 text-secondary" />
              <h3 className="font-bold text-xl">Preset Configurations</h3>
              <p className="text-center text-muted-foreground">
                Save and load your favorite display configurations with a single click.
              </p>
            </div>
          </div>
        </section>
        <section id="testimonials" className="px-6 py-20">
          <div className="gap-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mx-auto max-w-5xl container">
            <div className="flex flex-col justify-between bg-gradient-to-b from-primary/40 to-primary/10 shadow-md p-6 rounded h-full">
              <blockquote className="font-medium text-lg">
                "I use this app every day and it's cut down on so much frustration. Can't wait to share it with you all!"
              </blockquote>
              <div className="flex items-center gap-4 mt-4">
                <img src="/AlexYellowProfilePhoto1024.png" alt="Avatar" className="rounded-full w-12 h-12" />
                <div>
                  <h4 className="font-bold">Alexander Templeton</h4>
                  <p className="text-muted-foreground text-sm">APM Engineer</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted px-6 py-6">
        <div className="flex justify-between items-center mx-auto max-w-5xl container">
          <p className="text-sm">&copy; 2024 DisplayMason. All rights reserved.</p>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function AppleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function BotIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function DiscIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function KeyboardIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 8h.01" />
      <path d="M12 12h.01" />
      <path d="M14 8h.01" />
      <path d="M16 12h.01" />
      <path d="M18 8h.01" />
      <path d="M6 8h.01" />
      <path d="M7 16h10" />
      <path d="M8 12h.01" />
      <rect width="20" height="16" x="2" y="4" rx="2" />
    </svg>
  )
}


function ScalingIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
      <path d="M14 15H9v-5" />
      <path d="M16 3h5v5" />
      <path d="M21 3 9 15" />
    </svg>
  )
}


function SettingsIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function SquareMIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M8 16V8l4 4 4-4v8" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
